export default {
  CLEAR_STATE_AUTH: 'CLEAR_STATE_AUTH',
  LOGIN_ACTION: 'LOGIN_ACTION',
  UPDATE_STATE_AUTH: 'UPDATE_STATE_AUTH',
  UPDATE_DASHBOARD_STATE: 'UPDATE_DASHBOARD_STATE',
  GET_DASHBOARD_ACTION: 'GET_DASHBOARD_ACTION',
  GET_TEMPLATE_ACTION: 'GET_TEMPLATE_ACTION',
  UPDATE_TEMPLATE_STATE: 'UPDATE_TEMPLATE_STATE',
  RESET_DASHBOARD_STATE: 'RESET_DASHBOARD_STATE'
}
